namespace Arius.Core.Tests.Shared.Storage;

/// <summary>Minimal decorator without an override for the raw name-prefix overload.</summary>
internal sealed class PassthroughBlobContainerService(IBlobContainerService inner) : IBlobContainerService
{
    public Task                           CreateContainerIfNotExistsAsync(CancellationToken cancellationToken = default)                                                                                                                                     => inner.CreateContainerIfNotExistsAsync(cancellationToken);
    public Task<UploadResult>             UploadAsync(RelativePath blobName, Stream content, IReadOnlyDictionary<string, string> metadata, BlobTier tier, string? contentType = null, bool overwrite = false, CancellationToken cancellationToken = default) => inner.UploadAsync(blobName, content, metadata, tier, contentType, overwrite, cancellationToken);
    public Task<Stream>                   OpenWriteAsync(RelativePath blobName, string? contentType = null, CancellationToken cancellationToken = default)                                                                                                   => inner.OpenWriteAsync(blobName, contentType, cancellationToken);
    public Task<DownloadResult>           DownloadAsync(RelativePath blobName, CancellationToken cancellationToken = default)                                                                                                                                => inner.DownloadAsync(blobName, cancellationToken);
    public Task<DownloadResult?>          TryDownloadAsync(RelativePath blobName, CancellationToken cancellationToken = default)                                                                                                                             => inner.TryDownloadAsync(blobName, cancellationToken);
    public Task<BlobMetadata>             GetMetadataAsync(RelativePath blobName, CancellationToken cancellationToken = default)                                                                                                                             => inner.GetMetadataAsync(blobName, cancellationToken);
    public IAsyncEnumerable<BlobListItem> ListAsync(RelativePath prefix, BlobListPrefixKind prefixKind = BlobListPrefixKind.DirectoryPrefix, bool includeMetadata = false, CancellationToken cancellationToken = default)                                    => inner.ListAsync(prefix, prefixKind, includeMetadata, cancellationToken);
    public Task                           SetMetadataAsync(RelativePath blobName, IReadOnlyDictionary<string, string> metadata, CancellationToken cancellationToken = default)                                                                               => inner.SetMetadataAsync(blobName, metadata, cancellationToken);
    public Task                           SetTierAsync(RelativePath blobName, BlobTier tier, CancellationToken cancellationToken = default)                                                                                                                  => inner.SetTierAsync(blobName, tier, cancellationToken);
    public Task                           CopyAsync(RelativePath sourceBlobName, RelativePath destinationBlobName, BlobTier destinationTier, RehydratePriority? rehydratePriority = null, CancellationToken cancellationToken = default)                     => inner.CopyAsync(sourceBlobName, destinationBlobName, destinationTier, rehydratePriority, cancellationToken);
    public Task                           DeleteAsync(RelativePath blobName, CancellationToken cancellationToken = default)                                                                                                                                  => inner.DeleteAsync(blobName, cancellationToken);
}